### PR TITLE
Highlight edited item by setting it selected in the grid

### LINKED ISSUE #176: Visual indication of the row edited.
Add visual indication of the row being edited. Probably sync selectedItems with activeItems.

### PR DESCRIPTION
**Pull request by tomivirkki**
Resolves #176 

Kapture 2019-10-22 at 16 33 22

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-crud/178)

### CODE REVIEW

**Comment by jouni** [comment]
My fear is that this could cause confusion for users if the application has customized the grid somehow, for example to allow the user to do some bulk editing actions on the items.

If the user has selected multiple items using the selection checkboxes, and then opens one item for individual editing, how can they recognize it from the other selected items?

**Comment by tomivirkki** [comment]
@jouni The selection is only applied for the internal grid because of the reason you mentioned (there might be additional selection-related logic to a custom grid) https://github.com/vaadin/vaadin-crud/pull/178/files#diff-6cc49a2943ab49ae9b41588bc89d35f2R660

This means that custom grid doesn't get any visual indication by default. With custom grids, it's the responsibility of the app logic to add highlighting where needed.

**Comment by jouni** [comment]
What I would want, is something like this:
Grid-focused-row

The same style would be great to show also when the user triggers a context menu for a row, but that’s outside the scope of this PR.

**Comment by jouni** [comment]
As the selection highlight is only applied for the default internal grid, and not for any custom slotted grids, we can go with that for now. Let’s try to get the row focus highlight implemented in a future version.

**Pull request merged**
