### PR TITLE
Do not revert toolbar order

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-crud/133)

### CODE REVIEW

**Comment by jouni** [comment]
Why is this change proposed? The buttons should be aligned to the right end of the toolbar, in both themes (and by default as well).

**Comment by oluwasayo** [comment]
Another perspective is how this is presented to Flow users. 
If they call `crud.setToolbar(footerText, newItemButton)` the content will appear in reverse order which is counter-intuitive. I don't think Flow users really want to know about `flex-direction`. Alternatives would be documenting this behavior in the Flow component or having the Flow component reverse the order but I'm not sure those are ideal solutions.

**Comment by jouni** [comment]
That’s a valid point, I agree. Applies to HTML as well. But I’m not sure if that is something absolute, that we need to obey always.

There are other similar cases, like an `AbsoluteLayout` where the order of the components in the source does not define the visual order. Or in `<vaadin-app-layout>`, the content and the navigation bar change visual order when the viewport size changes. Same with `<vaadin-confirm-dialog>`.

Still, worth thinking how we can mitigate these potential confusions and mental-model mismatches.

**Comment by jouni** [comment]
> the change does not change any UX

But it does change it, at least a little. In the editor dialog, when tabbing through the form, the `Delete…` button will be focused first, instead of the `Save` button. To latter seemed to me the better option, but it might be irrelevant if we implement #128 (click the Save button when pressing the Enter key inside the form).

**Comment by jouni** [comment]
I think I’m okay with this change, at least for now. At least the macOS confirm dialog works in this way (the Cancel button is focused before the OK button). 

As a counter example, the Comment button here in GitHub is focused before the Close and commetn button.

**Pull request merged**
